--- Sentencias SQL para la creaci�n del esquema de EPSAndes

-- USO
-- Copie el contenido de este archivo en una pesta�a SQL de SQL Developer
-- Ejec�telo como un script - Utilice el bot�n correspondiente de la pesta�a utilizada

--Eliminacion de tablas Y SECUENCIAS
DROP SEQUENCE EPSANDES_SEQUENCE;

DROP TABLE CONSULTA;
DROP TABLE HOSPITALIZACION;
DROP TABLE PROCEDIMIENTO;
DROP TABLE TERAPIA;
DROP TABLE EXAMEN_DIAGNOSTICO;
DROP TABLE RESERVA;
DROP TABLE HORARIO;
DROP TABLE ORDEN;
DROP TABLE TRABAJA_EN;
DROP TABLE PARTICIPAN;
DROP TABLE RECEPCIONISTA;
DROP TABLE AFILIADO;
DROP TABLE MEDICO;
DROP TABLE SERVICIO_SALUD;
DROP TABLE IPS;
DROP TABLE USUARIO;
DROP TABLE CAMPANA;
DROP TABLE SERVICIO_DESHABILITADO;
DROP TABLE TIPO_CONSULTA;
DROP TABLE TIPO_SERVICIO;
DROP TABLE TIPO_ID;
DROP TABLE ROL;

-- Creaci�n del secuenciador
create sequence epsandes_sequence;

-- Creaaci�n de la tabla TipoServicio y especificaci�n de sus restricciones
CREATE TABLE TIPO_SERVICIO
   (ID_SERVICIO NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
	CONSTRAINT TIPO_SERVICIO_PK PRIMARY KEY (ID_SERVICIO));
	
ALTER TABLE TIPO_SERVICIO
	ADD CONSTRAINT UN_TIPO_SERVICIO_NOMBRE 
	UNIQUE (NOMBRE)
ENABLE;

-- Creaaci�n de la tabla TIPO_ID y especificaci�n de sus restricciones
CREATE TABLE TIPO_ID
   (ID_TIPO NUMBER, 
	NOMBRE VARCHAR2(50 BYTE) NOT NULL,
	CONSTRAINT TIPO_ID_PK PRIMARY KEY (ID_TIPO));
	
ALTER TABLE TIPO_ID
    ADD CONSTRAINT UN_TIPO_ID_NOMBRE
    UNIQUE(NOMBRE)
ENABLE;

-- Creaci�n de la tabla TIPO_CONSULTA y especificaci�n de sus restricciones
CREATE TABLE TIPO_CONSULTA
   (ID_TIPO NUMBER,
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
	CONSTRAINT TIPO_CONSULTA_PK PRIMARY KEY (ID_TIPO));
	 
ALTER TABLE TIPO_CONSULTA
    ADD CONSTRAINT UN_TIPO_CONSULTA_NOMBRE
    UNIQUE(NOMBRE)
ENABLE;

-- Creaci�n de la tabla ROL y especificaci�n de sus restricciones
CREATE TABLE ROL
   (ID_ROL NUMBER,
	ROL VARCHAR2(255 BYTE) NOT NULL,
	CONSTRAINT ROL_PK PRIMARY KEY (ID_ROL));
	 
ALTER TABLE ROL
    ADD CONSTRAINT UN_ROL_ROL
    UNIQUE(ROL)
ENABLE;

-- Creaci�n de la tabla IPS y especificaci�n de sus restricciones
CREATE TABLE IPS
   (ID_IPS NUMBER,
	NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
	LOCALIZACION VARCHAR2(255 BYTE) NOT NULL, 
	CONSTRAINT IPS_PK PRIMARY KEY (ID_IPS));

-- Creaaci�n de la tabla USUARIO y especificaci�n de sus restricciones
CREATE TABLE USUARIO
   (ID_USUARIO NUMBER,
	NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
    CORREO VARCHAR2(255 BYTE) NOT NULL,
    ID NUMBER NOT NULL,
    TIPO_ID NUMBER NOT NULL,
    ROL NUMBER NOT NULL,
	CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO));

ALTER TABLE USUARIO
    ADD CONSTRAINT UN_USUARIO_CORREO
    UNIQUE(CORREO)
ENABLE;

ALTER TABLE USUARIO
    ADD CONSTRAINT CK_USUARIO_CORREO
    CHECK(CORREO LIKE '%@%.%')
ENABLE;

ALTER TABLE USUARIO
    ADD CONSTRAINT UN_USUARIO_ID
    UNIQUE(ID)
ENABLE;

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_TIPO_ID
    FOREIGN KEY (TIPO_ID)
    REFERENCES TIPO_ID(ID_TIPO)
ENABLE;
    
ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_ROL
    FOREIGN KEY (ROL)
    REFERENCES ROL(ID_ROL)
ENABLE;

-- Creaci�n de la tabla AFILIADO y especificaci�n de sus restricciones
CREATE TABLE AFILIADO
   (ID_AFILIADO NUMBER,
	FECHA_NACIMIENTO TIMESTAMP NOT NULL, 
	USUARIO NUMBER NOT NULL, 
	CONSTRAINT AFILIADO_PK PRIMARY KEY (ID_AFILIADO));

ALTER TABLE AFILIADO
	ADD CONSTRAINT FK_AFILIADO_USUARIO 
	FOREIGN KEY (USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
ENABLE;

-- Creaci�n de la tabla MEDICO y especificaci�n de sus restricciones
CREATE TABLE MEDICO
   (ID_MEDICO NUMBER,
	REGISTRO_MEDICO NUMBER NOT NULL, 
    ESPECIALIDAD VARCHAR2(255 BYTE) NOT NULL,
	USUARIO NUMBER NOT NULL, 
	CONSTRAINT MEDICO_PK PRIMARY KEY (ID_MEDICO));

ALTER TABLE MEDICO
    ADD CONSTRAINT UN_MEDICO_RGMED
    UNIQUE(REGISTRO_MEDICO)
ENABLE;

-- Creaci�n de la tabla RECEPCIONISTA y especificaci�n de sus restricciones
CREATE TABLE RECEPCIONISTA
   (ID_RECEPCIONISTA NUMBER,
	USUARIO NUMBER NOT NULL, 
    IPS NUMBER NOT NULL,
	CONSTRAINT RECEPCIONISTA_PK PRIMARY KEY (ID_RECEPCIONISTA));

ALTER TABLE RECEPCIONISTA
	ADD CONSTRAINT FK_RECEPCIONISTA_USUARIO 
	FOREIGN KEY (USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
ENABLE;

ALTER TABLE RECEPCIONISTA
	ADD CONSTRAINT FK_RECEPCIONISTA_IPS
	FOREIGN KEY (IPS)
    REFERENCES IPS(ID_IPS)
ENABLE;

-- Creaci�n de la tabla TRABAJA_EN y especificaci�n de sus restricciones
CREATE TABLE TRABAJA_EN
   (IPS NUMBER,
	MEDICO NUMBER,
	CONSTRAINT TRABAJA_EN_PK PRIMARY KEY (IPS, MEDICO));

ALTER TABLE TRABAJA_EN
	ADD CONSTRAINT FK_TRABAJA_EN_IPS
	FOREIGN KEY (IPS)
    REFERENCES IPS(ID_IPS)
ENABLE;

ALTER TABLE TRABAJA_EN
	ADD CONSTRAINT FK_TRABAJA_EN_MEDICO
	FOREIGN KEY (MEDICO)
    REFERENCES MEDICO(ID_MEDICO)
ENABLE;

-- Creaci�n de la tabla SERVICIO_SALUD y especificaci�n de sus restricciones
CREATE TABLE SERVICIO_SALUD
   (ID_SERVICIO NUMBER,
	NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
	TIPO NUMBER NOT NULL, 
	CONSTRAINT SERVICIO_SALUD_PK PRIMARY KEY (ID_SERVICIO));

ALTER TABLE SERVICIO_SALUD
    ADD CONSTRAINT UN_SERVICIO_SALUD_NOMBRE
    UNIQUE(NOMBRE)
ENABLE;

ALTER TABLE SERVICIO_SALUD
	ADD CONSTRAINT FK_SERVICIO_SALUD_TIPO
	FOREIGN KEY (TIPO)
    REFERENCES TIPO_SERVICIO(ID_SERVICIO)
ENABLE;

-- Creaci�n de la tabla ORDEN y especificaci�n de sus restricciones
CREATE TABLE ORDEN
   (CODIGO NUMBER,
	FECHA TIMESTAMP NOT NULL, 
    VALIDO NUMBER(1, 0) NOT NULL,
    MEDICO_REMIT NUMBER NOT NULL,
    SERVICIO NUMBER NOT NULL,
    AFILIADO NUMBER NOT NULL,
	CONSTRAINT ORDEN_PK PRIMARY KEY (CODIGO));
    
ALTER TABLE ORDEN
	ADD CONSTRAINT CK_ORDEN_VALIDO
    CHECK (VALIDO IN (0, 1))
ENABLE;

ALTER TABLE ORDEN
	ADD CONSTRAINT FK_ORDEN_MEDREM
	FOREIGN KEY (MEDICO_REMIT)
    REFERENCES MEDICO(ID_MEDICO)
ENABLE;

ALTER TABLE ORDEN
	ADD CONSTRAINT FK_ORDEN_SERVICIO
	FOREIGN KEY (SERVICIO)
    REFERENCES SERVICIO_SALUD(ID_SERVICIO)
ENABLE;

ALTER TABLE ORDEN
	ADD CONSTRAINT FK_ORDEN_AFILIADO
	FOREIGN KEY (AFILIADO)
    REFERENCES AFILIADO(ID_AFILIADO)
ENABLE;

-- Creaci�n de la tabla ServicioDeshabilitado y especificaci�n de sus restricciones
CREATE TABLE SERVICIO_DESHABILITADO
    (ID NUMBER,
     FECHA_INICIO TIMESTAMP NOT NULL,
     FECHA_FIN TIMESTAMP NOT NULL,
     CONSTRAINT SERVICIO_DESHABILITADO_PK PRIMARY KEY (ID));
     
-- Creaci�n de la tabla Campana y especificaci�n de sus restricciones
CREATE TABLE CAMPANA
    (ID_CAMPANA NUMBER,
     CANCELADA NUMBER(1, 0),
     FECHA_INICIO TIMESTAMP NOT NULL,
     FECHA_FIN TIMESTAMP NOT NULL,
     CONSTRAINT CAMPANA_PK PRIMARY KEY (ID_CAMPANA));
     
ALTER TABLE CAMPANA
	ADD CONSTRAINT CK_CAMPANA_CANCELADA
    CHECK (CANCELADA IN (0, 1))
ENABLE;

-- Creaci�n de la tabla Participan y especificaci�n de sus restricciones

CREATE TABLE PARTICIPAN
   (AFILIADO NUMBER,
	CAMPANA NUMBER,
	CONSTRAINT PARTICIPAN_PK PRIMARY KEY (AFILIADO, CAMPANA));

ALTER TABLE PARTICIPAN
	ADD CONSTRAINT FK_PARTICIPAN_AFILIADO
	FOREIGN KEY (AFILIADO)
    REFERENCES AFILIADO(ID_AFILIADO)
ENABLE;

ALTER TABLE PARTICIPAN
	ADD CONSTRAINT FK_PARTICIPAN_CAMPANA
	FOREIGN KEY (CAMPANA)
    REFERENCES CAMPANA(ID_CAMPANA)
ENABLE;

-- Creaci�n de la tabla Horario y especificaci�n de sus restricciones
CREATE TABLE HORARIO
   (ID_HORARIO NUMBER,
	IPS NUMBER NOT NULL,
    SERVICIO NUMBER NOT NULL,
    CAPACIDAD NUMBER NOT NULL,
    DIA NUMBER(1, 0) NOT NULL,
    HORA_INICIO TIMESTAMP NOT NULL,
    HORA_FIN TIMESTAMP NOT NULL,
    DESHABILITADO NUMBER,
	CONSTRAINT HORARIO_PK PRIMARY KEY (ID_HORARIO));
    
ALTER TABLE HORARIO
	ADD CONSTRAINT CK_HORARIO_DIA
    CHECK (DIA BETWEEN 1 AND 7)
ENABLE;

ALTER TABLE HORARIO
	ADD CONSTRAINT FK_HORARIO_IPS
	FOREIGN KEY (IPS)
    REFERENCES IPS(ID_IPS)
ENABLE;

ALTER TABLE HORARIO
	ADD CONSTRAINT FK_HORARIO_SERVICIO
	FOREIGN KEY (SERVICIO)
    REFERENCES SERVICIO_SALUD(ID_SERVICIO)
ENABLE;

ALTER TABLE HORARIO
	ADD CONSTRAINT FK_HORARIO_DESHABILITADO
	FOREIGN KEY (DESHABILITADO)
    REFERENCES SERVICIO_DESHABILITADO(ID)
ENABLE;

-- Creaci�n de la tabla RESERVA y especificaci�n de sus restricciones
CREATE TABLE RESERVA
   (CODIGO NUMBER,
    SERVICIO_PRESTADO NUMBER(1,0) NOT NULL,
    AFILIADO NUMBER NOT NULL,
    ORDEN NUMBER NOT NULL,
    HORARIO NUMBER NOT NULL,
	FECHA TIMESTAMP NOT NULL,
    CAMPANA NUMBER,
	CONSTRAINT RESERVA_PK PRIMARY KEY (CODIGO));
    
ALTER TABLE RESERVA
	ADD CONSTRAINT CK_RESERVA_SERPRES
    CHECK (SERVICIO_PRESTADO IN (0, 1))
ENABLE;

ALTER TABLE RESERVA
    ADD CONSTRAINT UN_RESERVA_ORDEN
    UNIQUE(ORDEN)
ENABLE;

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_AFILIADO
	FOREIGN KEY (AFILIADO)
    REFERENCES AFILIADO(ID_AFILIADO)
ENABLE;

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_ORDEN
	FOREIGN KEY (ORDEN)
    REFERENCES ORDEN(CODIGO)
ENABLE;

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_HORARIO
	FOREIGN KEY (HORARIO)
    REFERENCES HORARIO(ID_HORARIO)
ENABLE;

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_CAMPANA
	FOREIGN KEY (CAMPANA)
    REFERENCES CAMPANA(ID_CAMPANA)
ENABLE;

-- Creaci�n de la tabla CONSULTA y especificaci�n de sus restricciones
CREATE TABLE CONSULTA
   (RESERVA NUMBER,
    OBSERVACION VARCHAR2(1000 BYTE) NOT NULL,
    PRIORIDAD NUMBER(1,0),
    RECETA VARCHAR2(255 BYTE),
    TIPO NUMBER NOT NULL,
	CONSTRAINT CONSULTA_PK PRIMARY KEY (RESERVA));
    
ALTER TABLE CONSULTA
	ADD CONSTRAINT CK_CONSULTA_PRIO
    CHECK (PRIORIDAD BETWEEN 1 AND 5)
ENABLE;

ALTER TABLE CONSULTA
	ADD CONSTRAINT FK_CONSULTA_RESERVA
	FOREIGN KEY (RESERVA)
    REFERENCES RESERVA(CODIGO)
ENABLE;

ALTER TABLE CONSULTA
	ADD CONSTRAINT FK_CONSULTA_TIPO
	FOREIGN KEY (TIPO)
    REFERENCES TIPO_CONSULTA(ID_TIPO)
ENABLE;

-- Creaci�n de la tabla EXAMEN_DIAGNOSTICO y especificaci�n de sus restricciones
CREATE TABLE EXAMEN_DIAGNOSTICO
   (RESERVA NUMBER,
    DIAGNOSTICO VARCHAR2(1000 BYTE) NOT NULL,
	CONSTRAINT EXAMEN_DIAGNOSTICO_PK PRIMARY KEY (RESERVA));
    
ALTER TABLE EXAMEN_DIAGNOSTICO
	ADD CONSTRAINT FK_EXAMEN_DIAGNOSTICO_RESERVA
	FOREIGN KEY (RESERVA)
    REFERENCES RESERVA(CODIGO)
ENABLE;

-- Creaci�n de la tabla TERAPIA y especificaci�n de sus restricciones
CREATE TABLE TERAPIA
   (RESERVA NUMBER,
    NUMERO_SESIONES NUMBER NOT NULL,
	CONSTRAINT TERAPIA_PK PRIMARY KEY (RESERVA));
    
ALTER TABLE TERAPIA
    ADD CONSTRAINT CK_TERAPIA_NUMSES
    CHECK (NUMERO_SESIONES > 0)
ENABLE;

ALTER TABLE TERAPIA
	ADD CONSTRAINT FK_TERAPIA_RESERVA
	FOREIGN KEY (RESERVA)
    REFERENCES RESERVA(CODIGO)
ENABLE;

-- Creaci�n de la tabla PROCEDIMIENTO y especificaci�n de sus restricciones
CREATE TABLE PROCEDIMIENTO
   (RESERVA NUMBER,
    DESCRIPCION VARCHAR2(1000 BYTE) NOT NULL,
	CONSTRAINT PROCEDIMIENTO_PK PRIMARY KEY (RESERVA));
    
ALTER TABLE PROCEDIMIENTO
	ADD CONSTRAINT FK_PROCEDIMIENTO_RESERVA
	FOREIGN KEY (RESERVA)
    REFERENCES RESERVA(CODIGO)
ENABLE;

-- Creaci�n de la tabla HOSPITALIZACION y especificaci�n de sus restricciones
CREATE TABLE HOSPITALIZACION
   (RESERVA NUMBER,
    FECHA_SALIDA TIMESTAMP,
    OBSERVACION VARCHAR2(1000 BYTE) NOT NULL,
	CONSTRAINT HOSPITALIZACION_PK PRIMARY KEY (RESERVA));
    
ALTER TABLE HOSPITALIZACION
	ADD CONSTRAINT FK_HOSPITALIZACION_RESERVA
	FOREIGN KEY (RESERVA)
    REFERENCES RESERVA(CODIGO)
ENABLE;

COMMIT;